### ISSUE TITLE
上映時間順のタイトル一覧が欲しい

### ISSUE THREAD

**Issue by gongo** [Tomohiro/okinawa_movie#1]
出先で「なんでもいいから今やってる映画見たいな」って時、
現在の形だと一つ一つタイトルに潜って時間を見ていかないといけないため、
タイトルのような機能が欲しい(スターシアターズのサイトにある「上映時間順に表示」のような機能)

**Comment by tomohiro** [comment]
memo: `SELECT title, theater, start FROM movies ORDER BY start;`
